name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📁 Documentation'
    label: 'docs'

exclude-labels:
  - 'chore'

autolabeler:
  - label: 'feature'
    branch:
      - '/feat[-/_].+/'
  - label: 'docs'
    branch:
      - '/docs[-/_].+/'
  - label: 'chore'
    branch:
      - '/chore[-/_].+/'
  - label: 'bug'
    branch:
      - '/fix[-/_].+/'
    title:
      - '/fix/i'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES