version: '3'

tasks:
  test:
    - uv run --frozen pytest -v __tests --html=temp/pytest-report.html

  build-npm:
    dir: vue_components/
    cmds: 
      - pnpm run build
    
  dist: 
    deps:
      - build-npm
    cmds: 
      - cmd /C del /f /q dist
      - uv build -o ./dist

  rel: 
    - task: dist
    - uv publish

  mypy: mypy ex4nicegui/