name: test
run-name: test Actions
on:
  workflow_dispatch:
  schedule:
   - cron: '0 0 * * *'
  pull_request:
    branches:
      - main
jobs:
  run-all-test:
    runs-on: ubuntu-latest
    needs: [import-correct]
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: run test
        timeout-minutes: 4
        run: pytest __tests/
        shell: bash


  import-correct:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env

      - name: run
        timeout-minutes: 1
        run: |
          python -c "import ex4nicegui;from ex4nicegui.reactive import rxui;from ex4nicegui import bi"
    