name: Ruff Code Check

on:
  workflow_call:

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies (with lint group)
        run: uv sync --only-group lint

      - name: Run Ruff Linting (Check Code Quality)
        run: |
          uvx ruff check .

      - name: Run Ruff Formatting Check
        run: |
          uvx ruff format . --check